### ISSUE TITLE
Extended spec

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/yspec#112]
# Summary 
As a user, I want to extend one `yspec` object with the contents of another `yspec` object loaded form a named yaml specification file. 

# Tests
- tests/testthat/test-extend.R
  - load spec with extensionload spec with extension
  - extend a yspec object
  - extension fails when common columns
  - extension fails when extension file doesn't exist

**Comment by barrettk** [comment]
Removed `extension fails when common columns`. Appears that test is not present anymore

**Comment by kylebaron** [comment]
Yeah; I ended up changing that behavior.
