### ISSUE TITLE
API functions for dots

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/yspec#46]

**Comment by kylebaron** [comment]
@KatherineKayMRG 

This filters based on dots plus a handful of items outside of dots


``` r
library(tidyverse)
library(yspec)

spec <- ys_load(ys_help$file(), verbose = FALSE)

ys_filter(spec,  "C" %in% values | unit =="kg") 
#>  name c d unit short             source           
#>  C    + + .    comment character ysdb_internal.yml
#>  WT   - - kg   weight            ysdb_internal.yml

spec$SCR$dots <- list(covariate = TRUE)
spec$BMI$dots <- list(covariate = TRUE)
spec$HT$dots <- list(covariate = TRUE)

ys_filter(spec,  "C" %in% values | unit =="kg" | covariate) 
#>  name c d unit  short             source           
#>  C    + + .     comment character ysdb_internal.yml
#>  WT   - - kg    weight            ysdb_internal.yml
#>  BMI  - - m2/kg BMI               ysdb_internal.yml
#>  SCR  - - mg/dL serum creatinine  .                
#>  HT   - - cm    height            ysdb_internal.yml

ys_filter(spec, unit=="kg" | col =="TAFD")
#>  name c d unit  short                 source           
#>  WT   - - kg    weight                ysdb_internal.yml
#>  TAFD - - hours time after first dose .
```

<sup>Created on 2021-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by KatherineKayMRG** [comment]
This is looking great! I particularly like all the ways you can request columns. 

I'm not sure I fully understand the `timelike` part though. Is that something you're defining in dots and then saying by default it should be FALSE? And why does the syntax for `timelike` look like `(spec, timelike, .default = list(timelike = FALSE)` but the `covariate` syntax works as `(spec,  covariate)`?

Also, will this work if I want to evaluate one condition as true and one as false? For example, filter all `covariate=T` and `time-varying=F`

What would be the most efficient way do something like pull in all covariates except one specific covariate. For example, recent I had to handle one covariate slightly differently in some plots and so ended up doing
```
catCovDF <- purrr::keep(spec,~ isTRUE(.x$dots$categorical)) %>% as.data.frame()
catCovNames <- catCovDF$name %>% as.character()
catCovarList = axis_col_labs(spec, catCovNames, title_case=T)
catDVol = catCovarList["D_VOLUME"]
catCovarList = catCovarList[!names(catCovarList) %in% c("D_VOLUME")]
```
would there be a better way to handle something like that here? For example, could there be a drop argument that let me drop D_VOLUME in this case?

**Comment by kylebaron** [comment]
I have `covariate` coded into the function as defaulting to `FALSE` so that it can always be checked.  yspec doesn't know about `timelike` so we have to provide some default (null) value to fill in there so when we check there is something to check.  This is something that you could program into the spec in `SETUP__:` to do that. 

For one as true and one as false:
```r
ys_filter(spec,  covariate & ! time_varying)
```
should work. 

To exclude

```r
ys_filter(spec, categorical & col != "D_VOLUME")
```

**Comment by kylebaron** [comment]
Closing this for the separate issues for specific functions.

**Comment by barrettk** [comment]
Removing this issue from milestone for creation of user stories
