### ISSUE TITLE
Handle NA when making factors

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/yspec#79]
# Summary
As a user, I want `ys_add_factors()` to look for missing values and optionally fill in a user-specified label in the factor levels.

# Tests

**Comment by barrettk** [comment]
@kylebaron There are a few issues where no test files are mentioned in this package. An easy way to fix this would be to remove these issues from milestones. If not, we wont be able to pull from these milestones at all. The milestones `v0.5.0` and `v0.5.1` have issues like that
